#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="/home/D31337m3/Orm_d31337m3"
MAILCOW_CONF="/opt/mailcow-dockerized/mailcow.conf"
OUT_FILE="${OUT_FILE:-${ROOT_DIR}/.env.mailcow.runtime}"
MAILCOW_API_BASE="${MAILCOW_API_BASE:-https://127.0.0.1:8444}"
MAIL_DOMAIN="${MAIL_DOMAIN:-d31337m3.com}"
PYTHON_BIN="${ROOT_DIR}/microservices/.venv/bin/python"

if [[ ! -f "$MAILCOW_CONF" ]]; then
  echo "Missing Mailcow config at $MAILCOW_CONF" >&2
  exit 1
fi
if [[ ! -x "$PYTHON_BIN" ]]; then
  echo "Python venv not found at $PYTHON_BIN" >&2
  exit 1
fi

DBROOT="$(sudo grep '^DBROOT=' "$MAILCOW_CONF" | cut -d= -f2-)"
if [[ -z "$DBROOT" ]]; then
  echo "Could not read DBROOT from $MAILCOW_CONF" >&2
  exit 1
fi

MAILCOW_API_KEY="$(sudo docker exec mailcowdockerized-mysql-mailcow-1 mysql -N -B -uroot -p"$DBROOT" -D mailcow -e "SELECT api_key FROM api WHERE access='rw' AND active=1 LIMIT 1;" 2>/dev/null || true)"
if [[ -z "$MAILCOW_API_KEY" ]]; then
  MAILCOW_API_KEY="$(openssl rand -hex 24)"
  sudo docker exec mailcowdockerized-mysql-mailcow-1 mysql -uroot -p"$DBROOT" -D mailcow -e "INSERT INTO api (api_key, allow_from, skip_ip_check, access, active, created) VALUES ('$MAILCOW_API_KEY', '127.0.0.1/32', 1, 'rw', 1, NOW());" >/dev/null
fi

MAILCOW_API_BASE="$MAILCOW_API_BASE" MAILCOW_API_KEY="$MAILCOW_API_KEY" MAIL_DOMAIN="$MAIL_DOMAIN" OUT_FILE="$OUT_FILE" "$PYTHON_BIN" - <<'PY'
import json
import os
import secrets
import ssl
import string
import urllib.error
import urllib.request

mailcow_api_base = os.environ["MAILCOW_API_BASE"].rstrip("/")
mailcow_api_key = os.environ["MAILCOW_API_KEY"]
mail_domain = os.environ["MAIL_DOMAIN"]
out_file = os.environ["OUT_FILE"]

mailboxes = ["support", "payments", "security"]
alphabet = string.ascii_letters + string.digits

def rand_pw(n=28):
    return "".join(secrets.choice(alphabet) for _ in range(n))

ssl_ctx = ssl.create_default_context()
ssl_ctx.check_hostname = False
ssl_ctx.verify_mode = ssl.CERT_NONE

passwords = {m: rand_pw() for m in mailboxes}

for local, pw in passwords.items():
    email = f"{local}@{mail_domain}"
    payload = {
        "attr": {
            "authsource": "mailcow",
            "password": pw,
            "password2": pw,
            "force_pw_update": False,
        },
        "items": [email],
    }
    req = urllib.request.Request(
        f"{mailcow_api_base}/api/v1/edit/mailbox",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "X-API-Key": mailcow_api_key,
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=20, context=ssl_ctx) as r:
            body = r.read().decode("utf-8")
    except urllib.error.HTTPError as e:
        raise SystemExit(f"mailbox update failed for {email}: HTTP {e.code}")
    except Exception as e:
        raise SystemExit(f"mailbox update failed for {email}: {e}")

    try:
        data = json.loads(body)
    except Exception:
        raise SystemExit(f"mailbox update returned invalid JSON for {email}")

    ok = False
    if isinstance(data, list):
        for item in data:
            if isinstance(item, dict) and str(item.get("type", "")).lower() == "success":
                ok = True
                break
    if not ok:
        raise SystemExit(f"mailbox update did not report success for {email}")

support_email = f"support@{mail_domain}"
lines = [
    "# Generated by scripts/rotate_mailcow_and_write_runtime_env.sh",
    "SMTP_ENABLED=true",
    "SMTP_HOST=smtp.d31337m3.com",
    "SMTP_PORT=465",
    f"SMTP_USERNAME={support_email}",
    f"SMTP_PASSWORD={passwords['support']}",
    f"SMTP_FROM={support_email}",
    f"MAILBOX_SUPPORT_EMAIL={support_email}",
    f"MAILBOX_SUPPORT_PASSWORD={passwords['support']}",
    f"MAILBOX_PAYMENTS_EMAIL=payments@{mail_domain}",
    f"MAILBOX_PAYMENTS_PASSWORD={passwords['payments']}",
    f"MAILBOX_SECURITY_EMAIL=security@{mail_domain}",
    f"MAILBOX_SECURITY_PASSWORD={passwords['security']}",
]

with open(out_file, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(json.dumps({"mailboxes_rotated": len(mailboxes), "env_file": out_file}))
PY

chmod 600 "$OUT_FILE"
